### ISSUE TITLE
Push-based rendering to avoid burning GPU

### ISSUE THREAD

**Issue by ctrueden** [scenerygraphics/scenery#161]
Scenery renders in an active loop at high FPS right now, which causes unnecessary work for the GPU. Would be great if it could push updates only as needed to avoid this situation:

![](https://i.imgur.com/IfOE5mJ.gif)

**Comment by skalarproduktraum** [comment]
Definitely a :+1: for the gif xD

**Comment by kephale** [comment]
This was brought up in the early days, then the retina MBP resolution dehancement was added which slightly reduced the problem for some cases.

I have to say +💯 for putting serious thought into this in the near future. Until this works, scenery-based apps cannot be realistically used with laptops running on battery, plus my computer has overloaded to the point of needing a hard restart multiple times because of accidentally leaving scenery windows open in the background and trying to use other programs.

**Comment by skalarproduktraum** [comment]
Just for the record, this has been fixed with #185
